/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package threadrelay;

/**
 *
 * @author gennaioli.davide
 */
public class Staffetta extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Staffetta.class.getName());
    ;
    private int prossimoRunner = 0;
    private boolean sospeso = false;
    private Corridori[] corridori = new Corridori[4];
    private Thread[] threads = new Thread[4];
    private javax.swing.JProgressBar[] bars;
    private javax.swing.JLabel[] lblPerc;
    private javax.swing.JLabel[] lblNome;

  private void aggiungiPainter(javax.swing.JProgressBar bar) {
    javax.swing.ImageIcon img = new javax.swing.ImageIcon(
        getClass().getResource("/threadrelay/runner_emoji.png")
    );

    // forza BasicProgressBarUI invece di Nimbus
    bar.setUI(new javax.swing.plaf.basic.BasicProgressBarUI() {
        @Override
        public void paint(java.awt.Graphics g, javax.swing.JComponent c) {
            // disegna sfondo
            g.setColor(java.awt.Color.LIGHT_GRAY);
            g.fillRect(0, 0, bar.getWidth(), bar.getHeight());
            
            // disegna riempimento barra
            int fillW = (int) ((double) bar.getValue() / bar.getMaximum() * bar.getWidth());
            g.setColor(new java.awt.Color(100, 149, 237)); // blu
            g.fillRect(0, 0, fillW, bar.getHeight());

            // disegna bordo
            g.setColor(java.awt.Color.GRAY);
            g.drawRect(0, 0, bar.getWidth() - 1, bar.getHeight() - 1);

            // disegna immagine o "Fine"
            int p = bar.getValue();
            if (p == 100) {
                java.awt.Graphics2D g2 = (java.awt.Graphics2D) g;
                g2.setFont(new java.awt.Font("Arial", java.awt.Font.BOLD, 14));
                java.awt.FontMetrics fm = g2.getFontMetrics();
                g2.setColor(java.awt.Color.BLACK);
                
            } else {
                int imgW = 32;
                int imgH = 32;
                int x = (int) ((double) p / bar.getMaximum() * (bar.getWidth() - imgW));
                int y = (bar.getHeight() - imgH) / 2;
                g.drawImage(img.getImage(), x, y, imgW, imgH, bar);
            }
        }
    });
}

public Staffetta() {
    initComponents();

    aggiungiPainter(jProgressBar1);
    aggiungiPainter(jProgressBar2);
    aggiungiPainter(jProgressBar3);
    aggiungiPainter(jProgressBar4);

    jSpinner1.setModel(new javax.swing.SpinnerListModel(new String[]{"Slow", "Regular", "Fast"}));

    bars = new javax.swing.JProgressBar[]{jProgressBar1, jProgressBar2, jProgressBar3, jProgressBar4};
    lblPerc = new javax.swing.JLabel[]{lblPercentuale1, lblPercentuale2, lblPercentuale3, lblPercentuale4};
    lblNome = new javax.swing.JLabel[]{lblConcorrente1, lblConcorrente2, lblConcorrente3, lblConcorrente4};
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jSpinner1 = new javax.swing.JSpinner();
        btnAvvia = new javax.swing.JButton();
        btnSospendi = new javax.swing.JButton();
        btnRiprendi = new javax.swing.JButton();
        btnFerma = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        lblConcorrente1 = new javax.swing.JLabel();
        lblPercentuale1 = new javax.swing.JLabel();
        lblConcorrente2 = new javax.swing.JLabel();
        lblPercentuale2 = new javax.swing.JLabel();
        lblConcorrente3 = new javax.swing.JLabel();
        lblPercentuale3 = new javax.swing.JLabel();
        lblConcorrente4 = new javax.swing.JLabel();
        lblPercentuale4 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jProgressBar1 = new javax.swing.JProgressBar();
        jProgressBar2 = new javax.swing.JProgressBar();
        jProgressBar3 = new javax.swing.JProgressBar();
        jProgressBar4 = new javax.swing.JProgressBar();

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnAvvia.setText("AVVIA");
        btnAvvia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAvviaActionPerformed(evt);
            }
        });

        btnSospendi.setText("SOSPENDI");
        btnSospendi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSospendiActionPerformed(evt);
            }
        });

        btnRiprendi.setText("RIPRENDI");
        btnRiprendi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRiprendiActionPerformed(evt);
            }
        });

        btnFerma.setText("FERMA");
        btnFerma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFermaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(76, 76, 76)
                .addComponent(jSpinner1, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(btnAvvia)
                .addGap(18, 18, 18)
                .addComponent(btnSospendi)
                .addGap(18, 18, 18)
                .addComponent(btnRiprendi)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnFerma)
                .addContainerGap(88, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(56, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jSpinner1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAvvia)
                    .addComponent(btnSospendi)
                    .addComponent(btnRiprendi)
                    .addComponent(btnFerma))
                .addGap(21, 21, 21))
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.PAGE_END);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(lblConcorrente2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblPercentuale2))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(lblConcorrente1)
                        .addGap(18, 18, 18)
                        .addComponent(lblPercentuale1)
                        .addGap(0, 6, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(lblConcorrente4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblPercentuale4))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(lblConcorrente3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblPercentuale3))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblConcorrente1)
                    .addComponent(lblPercentuale1))
                .addGap(46, 46, 46)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblConcorrente2)
                    .addComponent(lblPercentuale2))
                .addGap(42, 42, 42)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblConcorrente3)
                    .addComponent(lblPercentuale3))
                .addGap(39, 39, 39)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblConcorrente4)
                    .addComponent(lblPercentuale4))
                .addContainerGap(111, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2, java.awt.BorderLayout.LINE_END);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jProgressBar4, javax.swing.GroupLayout.DEFAULT_SIZE, 495, Short.MAX_VALUE)
                    .addComponent(jProgressBar3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jProgressBar2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jProgressBar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(88, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(jProgressBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jProgressBar2, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jProgressBar3, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jProgressBar4, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(36, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel4, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSospendiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSospendiActionPerformed
        for (Corridori c : corridori) {
            if (c != null) {
                c.setSospeso(true);
            }
        }
    }//GEN-LAST:event_btnSospendiActionPerformed

    private void btnFermaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFermaActionPerformed
        // TODO add your handling code here:

        for (Corridori c : corridori) {
            if (c != null) {
                c.setFermato(true);
            }
        }

        for (Corridori c : corridori) {
            if (c != null) {
                c.setSospeso(false);
            }
        }
        Corridori.contatoreThread = 0;
        jSpinner1.setEnabled(true);
    }//GEN-LAST:event_btnFermaActionPerformed

    private void btnAvviaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAvviaActionPerformed
        // TODO add your handling code here:
        Corridori.contatoreThread = 0;
        jSpinner1.setEnabled(false);
        for (int i = 0; i < 4; i++) {
            bars[i].setValue(0);
            lblPerc[i].setText("0%");
            lblNome[i].setText("-");
        }
        avviaRunner(0);
    }//GEN-LAST:event_btnAvviaActionPerformed

    private void btnRiprendiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRiprendiActionPerformed
        for (Corridori c : corridori) {
            if (c != null) {
                c.setSospeso(false);
            }
        }
    }//GEN-LAST:event_btnRiprendiActionPerformed

    public int getVelocita() {
        String v = jSpinner1.getValue().toString();
        return switch (v) {
            case "Slow" ->
                80;
            case "Fast" ->
                10;
            default ->
                30;
        };
    }

    public void avviaRunner(int i) {
        if (i >= 4) {
            return;
        }
        lblNome[i].setText("Runner " + (i + 1));
        corridori[i] = new Corridori(bars[i], lblPerc[i], this);
        threads[i] = new Thread(corridori[i]);
        threads[i].start();
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Staffetta().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAvvia;
    private javax.swing.JButton btnFerma;
    private javax.swing.JButton btnRiprendi;
    private javax.swing.JButton btnSospendi;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JProgressBar jProgressBar2;
    private javax.swing.JProgressBar jProgressBar3;
    private javax.swing.JProgressBar jProgressBar4;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JLabel lblConcorrente1;
    private javax.swing.JLabel lblConcorrente2;
    private javax.swing.JLabel lblConcorrente3;
    private javax.swing.JLabel lblConcorrente4;
    private javax.swing.JLabel lblPercentuale1;
    private javax.swing.JLabel lblPercentuale2;
    private javax.swing.JLabel lblPercentuale3;
    private javax.swing.JLabel lblPercentuale4;
    // End of variables declaration//GEN-END:variables
}
